zerocam_ui/video/urls.py
from django.urls import path

from . import views

app_name = 'video'
urlpatterns = [
    path('', views.index, name='index'),
    path('live', views.live, name='live'),
]

zerocam_ui/wifi_setup/urls.py
from django.urls import path

from . import views

app_name = 'wifi_setup'
urlpatterns = [
    path('', views.index, name='index'),
    path('form-submit', views.form_submit, name='form_submit'),
    path('live', views.live, name='live'),
]

zerocam_ui/zerocam_ui/urls.py
from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.urls import include, path

urlpatterns = [
    path('wifi-setup/', include('wifi_setup.urls')),
    path('video/', include('video.urls')),
    path('admin/', admin.site.urls),
]

zerocam_ui/video/models.py
from django.db import models

# Create your models here.

zerocam_ui/video/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

import shlex
from subprocess import Popen
from subprocess import run
from subprocess import PIPE

from time import sleep

def index(request):
    template = loader.get_template('video-index.html')

    context = {
    }
    
    return HttpResponse(template.render(context, request))

def live(request):
    #sleep(5)
    template = loader.get_template('video-live.html')

    btnpicamstate = request.GET.get("btnpicamstate", "")

    btnpicamstatechange = False
    if btnpicamstate == 'on':
        btnpicamstatechange = True
        pscmd = shlex.split("sudo systemctl start picam.service")
        run(pscmd)
    if btnpicamstate == 'off':
        btnpicamstatechange = True
        pscmd = shlex.split("sudo systemctl stop picam.service")
        run(pscmd)
    if btnpicamstatechange:
        sleep(2)

    pscmd = shlex.split("systemctl is-active picam.service")
    picamstaterun = run(pscmd, stdout=PIPE)
    picamstaterunout = picamstaterun.stdout.decode('utf-8')
    if "inactive" in picamstaterunout:
        picamstate = False # "off"
    elif "active" in picamstaterunout:
        picamstate = True #"on"
    else:
        picamstate = None #"undefined"

    context = {
        "btnpicamstate" : btnpicamstate,
        "picamstate" : picamstate
    }

    return HttpResponse(template.render(context, request))

zerocam_ui/wifi_setup/views.py
# from django.shortcuts import render

# # Create your views here.

from django.http import HttpResponse
from django.template import loader

import shlex
from subprocess import Popen
from subprocess import run
from time import sleep

def index(request):
    template = loader.get_template('index.html')

    context = {
        'latest_question_list': 'Hi wie gehts',
    }
    return HttpResponse(template.render(context, request))

def form_submit(request):
    # template = loader.get_template('response.html')

    # context = {
    # }

    ssid="'" + request.POST.get("ssid", "") + "'"
    password="'" + request.POST.get("password", "") + "'"

    #print("SSID=","ssid"," Passwort=","password")
    pscmd = shlex.split("sudo /home/pi/zerocam/script/switchap.sh wifi " + ssid + " " + password)
    run(pscmd)

    # return HttpResponse(template.render(context, request))

zerocam_ui/video/templates/video-index.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/video-style.css' %}">

<div class="container">
    <h1>Willkommen im Video Bereich</h1>

    <div class="row margin-top-lg">
        <div class="col-xs-6 col-sm-4 col-lg-3">
            <a class="video-navigation-option text-center" href="{% url 'video:live' %}">
                <span class="video-navigation-icon glyphicon glyphicon-facetime-video" aria-hidden="true"></span>
                <span class="video-navigation-text">
                    Live Stream
                </span>
            </a>
        </div>
        <div class="col-xs-6 col-sm-4 col-lg-3">
            <a class="video-navigation-option text-center" href="{% url 'video:live' %}">
                <span class="video-navigation-icon glyphicon glyphicon-cloud" aria-hidden="true"></span>
                <span class="video-navigation-text">
                    Time Lapse
                </span>
            </a>
        </div>
        <div class="col-xs-6 col-sm-4 col-lg-3">
            <a class="video-navigation-option text-center" href="{% url 'wifi_setup:index' %}">
                <span class="video-navigation-icon glyphicon glyphicon-cog" aria-hidden="true"></span>
                <span class="video-navigation-text">
                    Settings
                </span>
            </a>
        </div>
        <div class="col-xs-6 col-sm-4 col-lg-3">
            <a class="video-navigation-option text-center" href="{% url 'admin:index' %}">
                <span class="video-navigation-icon glyphicon glyphicon-user" aria-hidden="true"></span>
                <span class="video-navigation-text">
                    Admin
                </span>
            </a>
        </div>
    </div>

</div>

zerocam_ui/video/templates/video-live.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<h1>Live-Stream</h1>


<!-- <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
<video id="video"></video>
<button onclick="play()">LOS</button>
<script>
    function play() {
        if(Hls.isSupported()) {
            var video = document.getElementById('video');
            var hls = new Hls();
            hls.loadSource("{% static 'video/index.m3u8' %}");
            hls.attachMedia(video);
            hls.on(Hls.Events.MANIFEST_PARSED,function() {
                video.play();
            });
        }
    }
</script> -->


<!-- CSS  -->
<link href="{% static 'css/video-js.css' %}" rel="stylesheet">

<!-- HTML -->
<video id='hls-player' class="video-js vjs-default-skin" width="400" height="300" controls>
    <source type="application/x-mpegURL" src="{% static 'video/index.m3u8' %}">
</video>

<!-- JS code -->
<script src="{% static 'js/videojs-contrib.hls.5.14.1.js' %}"></script>
<script src="{% static 'js/video.js' %}"></script>
<script>
    var player = videojs('hls-player');
    player.play();
</script>

<br>
<a class="btn btn-primary" href="/video/live">Reload</a>

<br>
<h3>picam control</h3>

<a class="btn btn-success" href="?btnpicamstate=on">ON</a>
<a class="btn btn-danger" href="?btnpicamstate=off">OFF</a>
<a class="btn {{ picamstate|yesno:"btn-danger,btn-success,btn-success" }}" href="?btnpicamstate={{ picamstate|yesno:"off,on,on" }}">{{ picamstate|yesno:"OFF,ON,Undefined" }}</a>

<h1>btnpicamstate</h1>
<h2>{{btnpicamstate}}</h1>
<br>
<h1>picamstate</h1>
<h2>{{picamstate}}</h2>

zerocam_ui/wifi_setup/templates/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="container">
    <div class="form-container">
        <h2>Please insert your WIFI Credentials</h2>
        <form action="{% url 'wifi_setup:form_submit' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="ssid">SSID</label>
                <input class="form-control" type="text" name="ssid" placeholder="SSID" id="ssid">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input class="form-control" type="text" name="password" placeholder="Password" id="password">
            </div>
            <button class="btn btn-success btn-block" type="submit">LOS</button>
        </form>
    </div>
</div>

zerocam_ui/wifi_setup/templates/live.html
{% load static %}
<h1>Live-Stream</h1>

<!-- <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
<video id="video"></video>
<button onclick="play()">LOS</button>
<script>
    function play() {
        if(Hls.isSupported()) {
            var video = document.getElementById('video');
            var hls = new Hls();
            hls.loadSource("{% static 'video/index.m3u8' %}");
            hls.attachMedia(video);
            hls.on(Hls.Events.MANIFEST_PARSED,function() {
                video.play();
            });
        }
    }
</script> -->


<!-- CSS  -->
<link href="{% static 'css/video-js.css' %}" rel="stylesheet">

<!-- HTML -->
<video id='hls-player' class="video-js vjs-default-skin" width="400" height="300" controls>
    <source type="application/x-mpegURL" src="{% static 'video/index.m3u8' %}">
</video>

<!-- JS code -->
<script src="{% static 'js/videojs-contrib.hls.5.14.1.js' %}"></script>
<script src="{% static 'js/video.js' %}"></script>
<script>
    var player = videojs('hls-player');
    player.play();
</script>